db:
  image: mysql
  ports:
    - "3306"
  environment:
     - MYSQL_ROOT_PASSWORD=verysecret
web:
  build: .
  command: php artisan serve --host=0.0.0.0 --port=8000
  volumes:
    - .:/app
  ports:
    - "8000:8000"
  links:
    - db
  env_file: .env
